Repository canonical/kubeflow-tensorboards-operator, pull requests merged in 2025-02, with the labels that each got.

#166 fix: fetch istio_gateway_info lib with charmcraft to match published lib
  charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
Labels: Libraries: Out of sync

#165 fix: use charmcraft promote in promote.yaml workflow
  .github/workflows/promote.yaml
Labels: Libraries: OK

#168 fix: fetch istio_gateway_info lib with charmcraft to match published lib (#166)
  charms/tensorboard-controller/lib/charms/istio_pilot/v0/istio_gateway_info.py
Labels: Libraries: Out of sync, backport

#167 [KF-7014] Use open requirements on terraform juju provider version sp…
  charms/tensorboard-controller/terraform/versions.tf
  charms/tensorboards-web-app/terraform/versions.tf
Labels: Libraries: Out of sync

#170 chore: upgrade to 1.10.0-rc.0
  charms/tensorboard-controller/metadata.yaml
  charms/tensorboards-web-app/metadata.yaml
Labels: Libraries: Out of sync

#171 chore: integrate 1.10.0-rc.0 rocks
  charms/tensorboard-controller/metadata.yaml
  charms/tensorboards-web-app/metadata.yaml
Labels: Libraries: Out of sync
